// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type LedgerLine struct {
	ID        int64
	Ts        time.Time
	Kind      string
	Provider  string
	Label     string
	Chars     int32
	InTokens  int32
	OutTokens int32
	CostUsd   float64
}

type Playlist struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PlaylistItem struct {
	PlaylistID string
	Position   int32
	YtID       string
}

type Station struct {
	ID               bool
	ActivePlaylistID pgtype.UUID
	OnAir            bool
	OnAirSince       *time.Time
	UpdatedAt        time.Time
}

type Track struct {
	YtID       string
	Title      string
	Channel    string
	DurationS  float64
	ArtifactID string
	InputI     float64
	InputTp    float64
	InputLra   float64
	AddedAt    time.Time
}
