// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AirLog struct {
	ID              int64
	YtID            string
	Title           string
	Artist          string
	StartedAt       time.Time
	DurationS       int32
	Source          string
	RequestedByName string
	Reason          string
}

type LedgerLine struct {
	ID        int64
	Ts        time.Time
	Kind      string
	Provider  string
	Label     string
	Chars     int32
	InTokens  int32
	OutTokens int32
	CostUsd   float64
}

type LlmCall struct {
	ID           int64
	Ts           time.Time
	Label        string
	Model        string
	Provider     string
	SystemPrompt string
	UserPrompt   string
	Output       string
	InTokens     int32
	OutTokens    int32
	CostUsd      float64
	LatencyMs    int32
	Error        string
	Fake         bool
}

type NextUp struct {
	ID        bool
	YtID      string
	Title     string
	Channel   string
	UpdatedAt time.Time
}

type RadioListener struct {
	SessionID string
	LastSeen  time.Time
}

type Request struct {
	ID           string
	Source       string
	RequestedBy  string
	DisplayName  string
	YtID         string
	Title        string
	Channel      string
	DurationS    int64
	ThumbnailUrl string
	Status       string
	FailReason   string
	Attempts     int32
	CreatedAt    time.Time
	AiredAt      *time.Time
	Reason       string
	Position     pgtype.Int4
}

type Station struct {
	ID             bool
	OnAir          bool
	OnAirSince     *time.Time
	UpdatedAt      time.Time
	AiEnabled      bool
	DjVoiceID      string
	DjRate         float64
	DjBreakEvery   int32
	DjStationIDMin int32
	DjMaxChars     int32
}

type Track struct {
	YtID         string
	Title        string
	Channel      string
	DurationS    float64
	ArtifactID   string
	InputI       float64
	InputTp      float64
	InputLra     float64
	AddedAt      time.Time
	TailSilenceS float64
	TailDecayS   float64
	SongKey      string
}
