// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"
)

const airHistory = `-- name: AirHistory :many
SELECT yt_id, title, artist, started_at, duration_s, source, requested_by_name, reason
FROM air_log
WHERE started_at + make_interval(secs => duration_s) < now()
ORDER BY started_at DESC
LIMIT $1
`

type AirHistoryRow struct {
	YtID            string
	Title           string
	Artist          string
	StartedAt       time.Time
	DurationS       int32
	Source          string
	RequestedByName string
	Reason          string
}

func (q *Queries) AirHistory(ctx context.Context, limit int32) ([]AirHistoryRow, error) {
	rows, err := q.db.Query(ctx, airHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AirHistoryRow{}
	for rows.Next() {
		var i AirHistoryRow
		if err := rows.Scan(
			&i.YtID,
			&i.Title,
			&i.Artist,
			&i.StartedAt,
			&i.DurationS,
			&i.Source,
			&i.RequestedByName,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const airedSince = `-- name: AiredSince :one
SELECT EXISTS(
  SELECT 1 FROM air_log WHERE yt_id = $1 AND started_at >= $2
)
`

type AiredSinceParams struct {
	YtID      string
	StartedAt time.Time
}

func (q *Queries) AiredSince(ctx context.Context, arg AiredSinceParams) (bool, error) {
	row := q.db.QueryRow(ctx, airedSince, arg.YtID, arg.StartedAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const allTrackIDs = `-- name: AllTrackIDs :many
SELECT yt_id FROM track ORDER BY yt_id
`

func (q *Queries) AllTrackIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, allTrackIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var yt_id string
		if err := rows.Scan(&yt_id); err != nil {
			return nil, err
		}
		items = append(items, yt_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const appendAirLog = `-- name: AppendAirLog :exec
INSERT INTO air_log (yt_id, title, artist, started_at, duration_s, source, requested_by_name, reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type AppendAirLogParams struct {
	YtID            string
	Title           string
	Artist          string
	StartedAt       time.Time
	DurationS       int32
	Source          string
	RequestedByName string
	Reason          string
}

func (q *Queries) AppendAirLog(ctx context.Context, arg AppendAirLogParams) error {
	_, err := q.db.Exec(ctx, appendAirLog,
		arg.YtID,
		arg.Title,
		arg.Artist,
		arg.StartedAt,
		arg.DurationS,
		arg.Source,
		arg.RequestedByName,
		arg.Reason,
	)
	return err
}

const appendPlaylistItem = `-- name: AppendPlaylistItem :execrows
INSERT INTO playlist_item (playlist_id, position, yt_id)
VALUES ($1,
        COALESCE((SELECT max(position) + 1 FROM playlist_item WHERE playlist_id = $1), 0),
        $2)
ON CONFLICT (playlist_id, yt_id) DO NOTHING
`

type AppendPlaylistItemParams struct {
	PlaylistID string
	YtID       string
}

func (q *Queries) AppendPlaylistItem(ctx context.Context, arg AppendPlaylistItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, appendPlaylistItem, arg.PlaylistID, arg.YtID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const beatListener = `-- name: BeatListener :exec
INSERT INTO radio_listener (session_id, last_seen) VALUES ($1, now())
ON CONFLICT (session_id) DO UPDATE SET last_seen = now()
`

func (q *Queries) BeatListener(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, beatListener, sessionID)
	return err
}

const bumpRequestAttempts = `-- name: BumpRequestAttempts :one
UPDATE request SET attempts = attempts + 1, fail_reason = $2 WHERE id = $1
RETURNING attempts
`

type BumpRequestAttemptsParams struct {
	ID         string
	FailReason string
}

func (q *Queries) BumpRequestAttempts(ctx context.Context, arg BumpRequestAttemptsParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpRequestAttempts, arg.ID, arg.FailReason)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const countListeners = `-- name: CountListeners :one
SELECT count(*) FROM radio_listener
WHERE last_seen > now() - interval '75 seconds'
`

func (q *Queries) CountListeners(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countListeners)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingByUser = `-- name: CountPendingByUser :one
SELECT count(*) FROM request
WHERE requested_by = $1 AND status IN ('approved', 'ready')
`

func (q *Queries) CountPendingByUser(ctx context.Context, requestedBy string) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingByUser, requestedBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlaylistItems = `-- name: CountPlaylistItems :one
SELECT count(*) FROM playlist_item WHERE playlist_id = $1
`

func (q *Queries) CountPlaylistItems(ctx context.Context, playlistID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPlaylistItems, playlistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsSince = `-- name: CountRequestsSince :one
SELECT count(*) FROM request WHERE requested_by = $1 AND created_at >= $2
`

type CountRequestsSinceParams struct {
	RequestedBy string
	CreatedAt   time.Time
}

func (q *Queries) CountRequestsSince(ctx context.Context, arg CountRequestsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsSince, arg.RequestedBy, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTracks = `-- name: CountTracks :one
SELECT count(*)
FROM track
WHERE ($1 = '' OR title ILIKE '%' || $1 || '%' OR channel ILIKE '%' || $1 || '%')
`

func (q *Queries) CountTracks(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countTracks, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO playlist (name) VALUES ($1)
RETURNING id::text AS id, name, created_at, updated_at
`

type CreatePlaylistRow struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreatePlaylist(ctx context.Context, name string) (CreatePlaylistRow, error) {
	row := q.db.QueryRow(ctx, createPlaylist, name)
	var i CreatePlaylistRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO request (source, requested_by, display_name, yt_id, title, channel, duration_s, thumbnail_url, status, reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id::text AS id, source, requested_by, display_name, yt_id, title, channel,
          duration_s, thumbnail_url, status, fail_reason, attempts, created_at, aired_at, reason
`

type CreateRequestParams struct {
	Source       string
	RequestedBy  string
	DisplayName  string
	YtID         string
	Title        string
	Channel      string
	DurationS    int64
	ThumbnailUrl string
	Status       string
	Reason       string
}

type CreateRequestRow struct {
	ID           string
	Source       string
	RequestedBy  string
	DisplayName  string
	YtID         string
	Title        string
	Channel      string
	DurationS    int64
	ThumbnailUrl string
	Status       string
	FailReason   string
	Attempts     int32
	CreatedAt    time.Time
	AiredAt      *time.Time
	Reason       string
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (CreateRequestRow, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.Source,
		arg.RequestedBy,
		arg.DisplayName,
		arg.YtID,
		arg.Title,
		arg.Channel,
		arg.DurationS,
		arg.ThumbnailUrl,
		arg.Status,
		arg.Reason,
	)
	var i CreateRequestRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.RequestedBy,
		&i.DisplayName,
		&i.YtID,
		&i.Title,
		&i.Channel,
		&i.DurationS,
		&i.ThumbnailUrl,
		&i.Status,
		&i.FailReason,
		&i.Attempts,
		&i.CreatedAt,
		&i.AiredAt,
		&i.Reason,
	)
	return i, err
}

const deleteAllPlaylistItems = `-- name: DeleteAllPlaylistItems :exec
DELETE FROM playlist_item WHERE playlist_id = $1
`

func (q *Queries) DeleteAllPlaylistItems(ctx context.Context, playlistID string) error {
	_, err := q.db.Exec(ctx, deleteAllPlaylistItems, playlistID)
	return err
}

const deletePlaylist = `-- name: DeletePlaylist :execrows
DELETE FROM playlist WHERE id = $1
`

func (q *Queries) DeletePlaylist(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlaylist, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePlaylistItem = `-- name: DeletePlaylistItem :execrows
DELETE FROM playlist_item WHERE playlist_id = $1 AND yt_id = $2
`

type DeletePlaylistItemParams struct {
	PlaylistID string
	YtID       string
}

func (q *Queries) DeletePlaylistItem(ctx context.Context, arg DeletePlaylistItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlaylistItem, arg.PlaylistID, arg.YtID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTrack = `-- name: DeleteTrack :one
DELETE FROM track WHERE yt_id = $1 RETURNING artifact_id
`

func (q *Queries) DeleteTrack(ctx context.Context, ytID string) (string, error) {
	row := q.db.QueryRow(ctx, deleteTrack, ytID)
	var artifact_id string
	err := row.Scan(&artifact_id)
	return artifact_id, err
}

const getPlaylistRow = `-- name: GetPlaylistRow :one
SELECT id::text AS id, name, created_at, updated_at
FROM playlist WHERE id = $1
`

type GetPlaylistRowRow struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetPlaylistRow(ctx context.Context, id string) (GetPlaylistRowRow, error) {
	row := q.db.QueryRow(ctx, getPlaylistRow, id)
	var i GetPlaylistRowRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStationRow = `-- name: GetStationRow :one
SELECT COALESCE(active_playlist_id::text, '')::text AS active_playlist_id, on_air, on_air_since
FROM station WHERE id = TRUE
`

type GetStationRowRow struct {
	ActivePlaylistID string
	OnAir            bool
	OnAirSince       *time.Time
}

// Station queries below use extra ::text casts that aren't semantically
// necessary in plain Postgres: sqlc's static analyzer (no live DB
// connection configured) can't otherwise infer a concrete Go type for
// COALESCE(uuid_col::text, ”) or for a bare uuid-column parameter, and
// falls back to interface{}/pgtype.UUID instead of the intended string.
// The outer ::text on the COALESCE reads (SELECT/RETURNING) and the
// ::text::uuid round-trip on the SetStationActive param are cast
// workarounds only — behavior is unchanged from a plain uuid column.
func (q *Queries) GetStationRow(ctx context.Context) (GetStationRowRow, error) {
	row := q.db.QueryRow(ctx, getStationRow)
	var i GetStationRowRow
	err := row.Scan(&i.ActivePlaylistID, &i.OnAir, &i.OnAirSince)
	return i, err
}

const getTrack = `-- name: GetTrack :one
SELECT yt_id, title, channel, duration_s, artifact_id, input_i, input_tp, input_lra, added_at
FROM track WHERE yt_id = $1
`

func (q *Queries) GetTrack(ctx context.Context, ytID string) (Track, error) {
	row := q.db.QueryRow(ctx, getTrack, ytID)
	var i Track
	err := row.Scan(
		&i.YtID,
		&i.Title,
		&i.Channel,
		&i.DurationS,
		&i.ArtifactID,
		&i.InputI,
		&i.InputTp,
		&i.InputLra,
		&i.AddedAt,
	)
	return i, err
}

const hasPendingYTID = `-- name: HasPendingYTID :one
SELECT EXISTS(
  SELECT 1 FROM request WHERE yt_id = $1 AND status IN ('approved', 'ready')
)
`

func (q *Queries) HasPendingYTID(ctx context.Context, ytID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingYTID, ytID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertLedgerLine = `-- name: InsertLedgerLine :exec
INSERT INTO ledger_line (ts, kind, provider, label, chars, in_tokens, out_tokens, cost_usd)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertLedgerLineParams struct {
	Ts        time.Time
	Kind      string
	Provider  string
	Label     string
	Chars     int32
	InTokens  int32
	OutTokens int32
	CostUsd   float64
}

func (q *Queries) InsertLedgerLine(ctx context.Context, arg InsertLedgerLineParams) error {
	_, err := q.db.Exec(ctx, insertLedgerLine,
		arg.Ts,
		arg.Kind,
		arg.Provider,
		arg.Label,
		arg.Chars,
		arg.InTokens,
		arg.OutTokens,
		arg.CostUsd,
	)
	return err
}

const insertPlaylistItemAt = `-- name: InsertPlaylistItemAt :exec
INSERT INTO playlist_item (playlist_id, position, yt_id) VALUES ($1, $2, $3)
`

type InsertPlaylistItemAtParams struct {
	PlaylistID string
	Position   int32
	YtID       string
}

func (q *Queries) InsertPlaylistItemAt(ctx context.Context, arg InsertPlaylistItemAtParams) error {
	_, err := q.db.Exec(ctx, insertPlaylistItemAt, arg.PlaylistID, arg.Position, arg.YtID)
	return err
}

const insertTrack = `-- name: InsertTrack :exec
INSERT INTO track (yt_id, title, channel, duration_s, artifact_id, input_i, input_tp, input_lra)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (yt_id) DO NOTHING
`

type InsertTrackParams struct {
	YtID       string
	Title      string
	Channel    string
	DurationS  float64
	ArtifactID string
	InputI     float64
	InputTp    float64
	InputLra   float64
}

func (q *Queries) InsertTrack(ctx context.Context, arg InsertTrackParams) error {
	_, err := q.db.Exec(ctx, insertTrack,
		arg.YtID,
		arg.Title,
		arg.Channel,
		arg.DurationS,
		arg.ArtifactID,
		arg.InputI,
		arg.InputTp,
		arg.InputLra,
	)
	return err
}

const latestAirLog = `-- name: LatestAirLog :one
SELECT id, yt_id, title, artist, started_at, duration_s, source, requested_by_name, reason
FROM air_log ORDER BY started_at DESC, id DESC LIMIT 1
`

func (q *Queries) LatestAirLog(ctx context.Context) (AirLog, error) {
	row := q.db.QueryRow(ctx, latestAirLog)
	var i AirLog
	err := row.Scan(
		&i.ID,
		&i.YtID,
		&i.Title,
		&i.Artist,
		&i.StartedAt,
		&i.DurationS,
		&i.Source,
		&i.RequestedByName,
		&i.Reason,
	)
	return i, err
}

const listLedgerLines = `-- name: ListLedgerLines :many
SELECT ts, kind, provider, label, chars, in_tokens, out_tokens, cost_usd
FROM ledger_line ORDER BY ts ASC
`

type ListLedgerLinesRow struct {
	Ts        time.Time
	Kind      string
	Provider  string
	Label     string
	Chars     int32
	InTokens  int32
	OutTokens int32
	CostUsd   float64
}

func (q *Queries) ListLedgerLines(ctx context.Context) ([]ListLedgerLinesRow, error) {
	rows, err := q.db.Query(ctx, listLedgerLines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedgerLinesRow{}
	for rows.Next() {
		var i ListLedgerLinesRow
		if err := rows.Scan(
			&i.Ts,
			&i.Kind,
			&i.Provider,
			&i.Label,
			&i.Chars,
			&i.InTokens,
			&i.OutTokens,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistItemIDs = `-- name: ListPlaylistItemIDs :many
SELECT yt_id FROM playlist_item WHERE playlist_id = $1 ORDER BY position
`

func (q *Queries) ListPlaylistItemIDs(ctx context.Context, playlistID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listPlaylistItemIDs, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var yt_id string
		if err := rows.Scan(&yt_id); err != nil {
			return nil, err
		}
		items = append(items, yt_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistItems = `-- name: ListPlaylistItems :many
SELECT ((row_number() OVER (ORDER BY pi.position)) - 1)::int AS position,
       pi.yt_id, t.title, t.channel, t.duration_s::bigint AS duration_s
FROM playlist_item pi
JOIN track t ON t.yt_id = pi.yt_id
WHERE pi.playlist_id = $1
ORDER BY pi.position
`

type ListPlaylistItemsRow struct {
	Position  int32
	YtID      string
	Title     string
	Channel   string
	DurationS int64
}

func (q *Queries) ListPlaylistItems(ctx context.Context, playlistID string) ([]ListPlaylistItemsRow, error) {
	rows, err := q.db.Query(ctx, listPlaylistItems, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaylistItemsRow{}
	for rows.Next() {
		var i ListPlaylistItemsRow
		if err := rows.Scan(
			&i.Position,
			&i.YtID,
			&i.Title,
			&i.Channel,
			&i.DurationS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistRows = `-- name: ListPlaylistRows :many
SELECT p.id::text AS id, p.name, p.created_at, p.updated_at,
       count(pi.yt_id)::int AS track_count,
       COALESCE(sum(t.duration_s), 0)::bigint AS total_duration_s
FROM playlist p
LEFT JOIN playlist_item pi ON pi.playlist_id = p.id
LEFT JOIN track t ON t.yt_id = pi.yt_id
GROUP BY p.id
ORDER BY p.created_at DESC
`

type ListPlaylistRowsRow struct {
	ID             string
	Name           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	TrackCount     int32
	TotalDurationS int64
}

func (q *Queries) ListPlaylistRows(ctx context.Context) ([]ListPlaylistRowsRow, error) {
	rows, err := q.db.Query(ctx, listPlaylistRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaylistRowsRow{}
	for rows.Next() {
		var i ListPlaylistRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrackCount,
			&i.TotalDurationS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracks = `-- name: ListTracks :many
SELECT yt_id, title, channel, duration_s, artifact_id, input_i, input_tp, input_lra, added_at
FROM track
WHERE ($1 = '' OR title ILIKE '%' || $1 || '%' OR channel ILIKE '%' || $1 || '%')
ORDER BY added_at DESC
LIMIT $2 OFFSET $3
`

type ListTracksParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

func (q *Queries) ListTracks(ctx context.Context, arg ListTracksParams) ([]Track, error) {
	rows, err := q.db.Query(ctx, listTracks, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Track{}
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.YtID,
			&i.Title,
			&i.Channel,
			&i.DurationS,
			&i.ArtifactID,
			&i.InputI,
			&i.InputTp,
			&i.InputLra,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStationRow = `-- name: LockStationRow :one
SELECT COALESCE(active_playlist_id::text, '')::text AS active_playlist_id, on_air, on_air_since
FROM station WHERE id = TRUE FOR UPDATE
`

type LockStationRowRow struct {
	ActivePlaylistID string
	OnAir            bool
	OnAirSince       *time.Time
}

func (q *Queries) LockStationRow(ctx context.Context) (LockStationRowRow, error) {
	row := q.db.QueryRow(ctx, lockStationRow)
	var i LockStationRowRow
	err := row.Scan(&i.ActivePlaylistID, &i.OnAir, &i.OnAirSince)
	return i, err
}

const markRequestAired = `-- name: MarkRequestAired :execrows
UPDATE request SET status = 'aired', aired_at = $2 WHERE id = $1
`

type MarkRequestAiredParams struct {
	ID      string
	AiredAt *time.Time
}

func (q *Queries) MarkRequestAired(ctx context.Context, arg MarkRequestAiredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRequestAired, arg.ID, arg.AiredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRequestFailed = `-- name: MarkRequestFailed :execrows
UPDATE request SET status = 'failed', fail_reason = $2 WHERE id = $1
`

type MarkRequestFailedParams struct {
	ID         string
	FailReason string
}

func (q *Queries) MarkRequestFailed(ctx context.Context, arg MarkRequestFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRequestFailed, arg.ID, arg.FailReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRequestReady = `-- name: MarkRequestReady :execrows
UPDATE request SET status = 'ready' WHERE id = $1 AND status = 'approved'
`

func (q *Queries) MarkRequestReady(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markRequestReady, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const nextReadyRequest = `-- name: NextReadyRequest :one
SELECT id::text AS id, source, requested_by, display_name, yt_id, title, channel,
       duration_s, thumbnail_url, status, fail_reason, attempts, created_at, aired_at, reason
FROM request WHERE status = 'ready'
ORDER BY (source = 'ai'), created_at, id LIMIT 1
`

type NextReadyRequestRow struct {
	ID           string
	Source       string
	RequestedBy  string
	DisplayName  string
	YtID         string
	Title        string
	Channel      string
	DurationS    int64
	ThumbnailUrl string
	Status       string
	FailReason   string
	Attempts     int32
	CreatedAt    time.Time
	AiredAt      *time.Time
	Reason       string
}

// Air order: listener requests FIFO, then AI picks FIFO — (source = 'ai')
// sorts false (listener) before true.
func (q *Queries) NextReadyRequest(ctx context.Context) (NextReadyRequestRow, error) {
	row := q.db.QueryRow(ctx, nextReadyRequest)
	var i NextReadyRequestRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.RequestedBy,
		&i.DisplayName,
		&i.YtID,
		&i.Title,
		&i.Channel,
		&i.DurationS,
		&i.ThumbnailUrl,
		&i.Status,
		&i.FailReason,
		&i.Attempts,
		&i.CreatedAt,
		&i.AiredAt,
		&i.Reason,
	)
	return i, err
}

const oldestApprovedRequest = `-- name: OldestApprovedRequest :one
SELECT id::text AS id, source, requested_by, display_name, yt_id, title, channel,
       duration_s, thumbnail_url, status, fail_reason, attempts, created_at, aired_at, reason
FROM request WHERE status = 'approved'
ORDER BY created_at, id LIMIT 1
`

type OldestApprovedRequestRow struct {
	ID           string
	Source       string
	RequestedBy  string
	DisplayName  string
	YtID         string
	Title        string
	Channel      string
	DurationS    int64
	ThumbnailUrl string
	Status       string
	FailReason   string
	Attempts     int32
	CreatedAt    time.Time
	AiredAt      *time.Time
	Reason       string
}

func (q *Queries) OldestApprovedRequest(ctx context.Context) (OldestApprovedRequestRow, error) {
	row := q.db.QueryRow(ctx, oldestApprovedRequest)
	var i OldestApprovedRequestRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.RequestedBy,
		&i.DisplayName,
		&i.YtID,
		&i.Title,
		&i.Channel,
		&i.DurationS,
		&i.ThumbnailUrl,
		&i.Status,
		&i.FailReason,
		&i.Attempts,
		&i.CreatedAt,
		&i.AiredAt,
		&i.Reason,
	)
	return i, err
}

const pendingRequests = `-- name: PendingRequests :many
SELECT id::text AS id, source, requested_by, display_name, yt_id, title, channel,
       duration_s, thumbnail_url, status, fail_reason, attempts, created_at, aired_at, reason
FROM request WHERE status IN ('approved', 'ready')
ORDER BY (source = 'ai'), created_at, id
`

type PendingRequestsRow struct {
	ID           string
	Source       string
	RequestedBy  string
	DisplayName  string
	YtID         string
	Title        string
	Channel      string
	DurationS    int64
	ThumbnailUrl string
	Status       string
	FailReason   string
	Attempts     int32
	CreatedAt    time.Time
	AiredAt      *time.Time
	Reason       string
}

func (q *Queries) PendingRequests(ctx context.Context) ([]PendingRequestsRow, error) {
	rows, err := q.db.Query(ctx, pendingRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingRequestsRow{}
	for rows.Next() {
		var i PendingRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.RequestedBy,
			&i.DisplayName,
			&i.YtID,
			&i.Title,
			&i.Channel,
			&i.DurationS,
			&i.ThumbnailUrl,
			&i.Status,
			&i.FailReason,
			&i.Attempts,
			&i.CreatedAt,
			&i.AiredAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const playlistStats = `-- name: PlaylistStats :one
SELECT count(pi.yt_id)::int AS track_count,
       COALESCE(sum(t.duration_s), 0)::bigint AS total_duration_s
FROM playlist_item pi
JOIN track t ON t.yt_id = pi.yt_id
WHERE pi.playlist_id = $1
`

type PlaylistStatsRow struct {
	TrackCount     int32
	TotalDurationS int64
}

func (q *Queries) PlaylistStats(ctx context.Context, playlistID string) (PlaylistStatsRow, error) {
	row := q.db.QueryRow(ctx, playlistStats, playlistID)
	var i PlaylistStatsRow
	err := row.Scan(&i.TrackCount, &i.TotalDurationS)
	return i, err
}

const pruneListeners = `-- name: PruneListeners :exec
DELETE FROM radio_listener WHERE last_seen < now() - interval '10 minutes'
`

func (q *Queries) PruneListeners(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneListeners)
	return err
}

const recentAirLogYTIDs = `-- name: RecentAirLogYTIDs :many
SELECT yt_id FROM air_log ORDER BY started_at DESC, id DESC LIMIT $1
`

func (q *Queries) RecentAirLogYTIDs(ctx context.Context, limit int32) ([]string, error) {
	rows, err := q.db.Query(ctx, recentAirLogYTIDs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var yt_id string
		if err := rows.Scan(&yt_id); err != nil {
			return nil, err
		}
		items = append(items, yt_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renamePlaylist = `-- name: RenamePlaylist :one
UPDATE playlist SET name = $2, updated_at = now() WHERE id = $1
RETURNING id::text AS id, name, created_at, updated_at
`

type RenamePlaylistParams struct {
	ID   string
	Name string
}

type RenamePlaylistRow struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) RenamePlaylist(ctx context.Context, arg RenamePlaylistParams) (RenamePlaylistRow, error) {
	row := q.db.QueryRow(ctx, renamePlaylist, arg.ID, arg.Name)
	var i RenamePlaylistRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requestsByUser = `-- name: RequestsByUser :many
SELECT id::text AS id, source, requested_by, display_name, yt_id, title, channel,
       duration_s, thumbnail_url, status, fail_reason, attempts, created_at, aired_at, reason
FROM request WHERE requested_by = $1
ORDER BY created_at DESC, id DESC LIMIT $2
`

type RequestsByUserParams struct {
	RequestedBy string
	Limit       int32
}

type RequestsByUserRow struct {
	ID           string
	Source       string
	RequestedBy  string
	DisplayName  string
	YtID         string
	Title        string
	Channel      string
	DurationS    int64
	ThumbnailUrl string
	Status       string
	FailReason   string
	Attempts     int32
	CreatedAt    time.Time
	AiredAt      *time.Time
	Reason       string
}

func (q *Queries) RequestsByUser(ctx context.Context, arg RequestsByUserParams) ([]RequestsByUserRow, error) {
	rows, err := q.db.Query(ctx, requestsByUser, arg.RequestedBy, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestsByUserRow{}
	for rows.Next() {
		var i RequestsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.RequestedBy,
			&i.DisplayName,
			&i.YtID,
			&i.Title,
			&i.Channel,
			&i.DurationS,
			&i.ThumbnailUrl,
			&i.Status,
			&i.FailReason,
			&i.Attempts,
			&i.CreatedAt,
			&i.AiredAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStationActive = `-- name: SetStationActive :exec
UPDATE station SET active_playlist_id = $1::text::uuid, updated_at = now() WHERE id = TRUE
`

func (q *Queries) SetStationActive(ctx context.Context, activePlaylistID string) error {
	_, err := q.db.Exec(ctx, setStationActive, activePlaylistID)
	return err
}

const stationGoOffAir = `-- name: StationGoOffAir :one
UPDATE station SET on_air = FALSE, on_air_since = NULL, updated_at = now() WHERE id = TRUE
RETURNING COALESCE(active_playlist_id::text, '')::text AS active_playlist_id, on_air, on_air_since
`

type StationGoOffAirRow struct {
	ActivePlaylistID string
	OnAir            bool
	OnAirSince       *time.Time
}

func (q *Queries) StationGoOffAir(ctx context.Context) (StationGoOffAirRow, error) {
	row := q.db.QueryRow(ctx, stationGoOffAir)
	var i StationGoOffAirRow
	err := row.Scan(&i.ActivePlaylistID, &i.OnAir, &i.OnAirSince)
	return i, err
}

const stationGoOnAir = `-- name: StationGoOnAir :one
UPDATE station SET on_air = TRUE, on_air_since = now(), updated_at = now() WHERE id = TRUE
RETURNING COALESCE(active_playlist_id::text, '')::text AS active_playlist_id, on_air, on_air_since
`

type StationGoOnAirRow struct {
	ActivePlaylistID string
	OnAir            bool
	OnAirSince       *time.Time
}

func (q *Queries) StationGoOnAir(ctx context.Context) (StationGoOnAirRow, error) {
	row := q.db.QueryRow(ctx, stationGoOnAir)
	var i StationGoOnAirRow
	err := row.Scan(&i.ActivePlaylistID, &i.OnAir, &i.OnAirSince)
	return i, err
}

const sumLedgerCost = `-- name: SumLedgerCost :one
SELECT COALESCE(SUM(cost_usd), 0)::double precision AS total FROM ledger_line
`

func (q *Queries) SumLedgerCost(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, sumLedgerCost)
	var total float64
	err := row.Scan(&total)
	return total, err
}

const sumLedgerCostSince = `-- name: SumLedgerCostSince :one
SELECT COALESCE(SUM(cost_usd), 0)::double precision AS total
FROM ledger_line WHERE ts >= $1
`

func (q *Queries) SumLedgerCostSince(ctx context.Context, ts time.Time) (float64, error) {
	row := q.db.QueryRow(ctx, sumLedgerCostSince, ts)
	var total float64
	err := row.Scan(&total)
	return total, err
}
