// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"
)

const appendPlaylistItem = `-- name: AppendPlaylistItem :execrows
INSERT INTO playlist_item (playlist_id, position, yt_id)
VALUES ($1,
        COALESCE((SELECT max(position) + 1 FROM playlist_item WHERE playlist_id = $1), 0),
        $2)
ON CONFLICT (playlist_id, yt_id) DO NOTHING
`

type AppendPlaylistItemParams struct {
	PlaylistID string
	YtID       string
}

func (q *Queries) AppendPlaylistItem(ctx context.Context, arg AppendPlaylistItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, appendPlaylistItem, arg.PlaylistID, arg.YtID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countPlaylistItems = `-- name: CountPlaylistItems :one
SELECT count(*) FROM playlist_item WHERE playlist_id = $1
`

func (q *Queries) CountPlaylistItems(ctx context.Context, playlistID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPlaylistItems, playlistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTracks = `-- name: CountTracks :one
SELECT count(*)
FROM track
WHERE ($1 = '' OR title ILIKE '%' || $1 || '%' OR channel ILIKE '%' || $1 || '%')
`

func (q *Queries) CountTracks(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countTracks, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO playlist (name) VALUES ($1)
RETURNING id::text AS id, name, created_at, updated_at
`

type CreatePlaylistRow struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreatePlaylist(ctx context.Context, name string) (CreatePlaylistRow, error) {
	row := q.db.QueryRow(ctx, createPlaylist, name)
	var i CreatePlaylistRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllPlaylistItems = `-- name: DeleteAllPlaylistItems :exec
DELETE FROM playlist_item WHERE playlist_id = $1
`

func (q *Queries) DeleteAllPlaylistItems(ctx context.Context, playlistID string) error {
	_, err := q.db.Exec(ctx, deleteAllPlaylistItems, playlistID)
	return err
}

const deletePlaylist = `-- name: DeletePlaylist :execrows
DELETE FROM playlist WHERE id = $1
`

func (q *Queries) DeletePlaylist(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlaylist, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePlaylistItem = `-- name: DeletePlaylistItem :execrows
DELETE FROM playlist_item WHERE playlist_id = $1 AND yt_id = $2
`

type DeletePlaylistItemParams struct {
	PlaylistID string
	YtID       string
}

func (q *Queries) DeletePlaylistItem(ctx context.Context, arg DeletePlaylistItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlaylistItem, arg.PlaylistID, arg.YtID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTrack = `-- name: DeleteTrack :one
DELETE FROM track WHERE yt_id = $1 RETURNING artifact_id
`

func (q *Queries) DeleteTrack(ctx context.Context, ytID string) (string, error) {
	row := q.db.QueryRow(ctx, deleteTrack, ytID)
	var artifact_id string
	err := row.Scan(&artifact_id)
	return artifact_id, err
}

const getPlaylistRow = `-- name: GetPlaylistRow :one
SELECT id::text AS id, name, created_at, updated_at
FROM playlist WHERE id = $1
`

type GetPlaylistRowRow struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetPlaylistRow(ctx context.Context, id string) (GetPlaylistRowRow, error) {
	row := q.db.QueryRow(ctx, getPlaylistRow, id)
	var i GetPlaylistRowRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStationRow = `-- name: GetStationRow :one
SELECT COALESCE(active_playlist_id::text, '')::text AS active_playlist_id, on_air, on_air_since
FROM station WHERE id = TRUE
`

type GetStationRowRow struct {
	ActivePlaylistID string
	OnAir            bool
	OnAirSince       *time.Time
}

func (q *Queries) GetStationRow(ctx context.Context) (GetStationRowRow, error) {
	row := q.db.QueryRow(ctx, getStationRow)
	var i GetStationRowRow
	err := row.Scan(&i.ActivePlaylistID, &i.OnAir, &i.OnAirSince)
	return i, err
}

const getTrack = `-- name: GetTrack :one
SELECT yt_id, title, channel, duration_s, artifact_id, input_i, input_tp, input_lra, added_at
FROM track WHERE yt_id = $1
`

func (q *Queries) GetTrack(ctx context.Context, ytID string) (Track, error) {
	row := q.db.QueryRow(ctx, getTrack, ytID)
	var i Track
	err := row.Scan(
		&i.YtID,
		&i.Title,
		&i.Channel,
		&i.DurationS,
		&i.ArtifactID,
		&i.InputI,
		&i.InputTp,
		&i.InputLra,
		&i.AddedAt,
	)
	return i, err
}

const insertLedgerLine = `-- name: InsertLedgerLine :exec
INSERT INTO ledger_line (ts, kind, provider, label, chars, in_tokens, out_tokens, cost_usd)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertLedgerLineParams struct {
	Ts        time.Time
	Kind      string
	Provider  string
	Label     string
	Chars     int32
	InTokens  int32
	OutTokens int32
	CostUsd   float64
}

func (q *Queries) InsertLedgerLine(ctx context.Context, arg InsertLedgerLineParams) error {
	_, err := q.db.Exec(ctx, insertLedgerLine,
		arg.Ts,
		arg.Kind,
		arg.Provider,
		arg.Label,
		arg.Chars,
		arg.InTokens,
		arg.OutTokens,
		arg.CostUsd,
	)
	return err
}

const insertPlaylistItemAt = `-- name: InsertPlaylistItemAt :exec
INSERT INTO playlist_item (playlist_id, position, yt_id) VALUES ($1, $2, $3)
`

type InsertPlaylistItemAtParams struct {
	PlaylistID string
	Position   int32
	YtID       string
}

func (q *Queries) InsertPlaylistItemAt(ctx context.Context, arg InsertPlaylistItemAtParams) error {
	_, err := q.db.Exec(ctx, insertPlaylistItemAt, arg.PlaylistID, arg.Position, arg.YtID)
	return err
}

const insertTrack = `-- name: InsertTrack :exec
INSERT INTO track (yt_id, title, channel, duration_s, artifact_id, input_i, input_tp, input_lra)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (yt_id) DO NOTHING
`

type InsertTrackParams struct {
	YtID       string
	Title      string
	Channel    string
	DurationS  float64
	ArtifactID string
	InputI     float64
	InputTp    float64
	InputLra   float64
}

func (q *Queries) InsertTrack(ctx context.Context, arg InsertTrackParams) error {
	_, err := q.db.Exec(ctx, insertTrack,
		arg.YtID,
		arg.Title,
		arg.Channel,
		arg.DurationS,
		arg.ArtifactID,
		arg.InputI,
		arg.InputTp,
		arg.InputLra,
	)
	return err
}

const listLedgerLines = `-- name: ListLedgerLines :many
SELECT ts, kind, provider, label, chars, in_tokens, out_tokens, cost_usd
FROM ledger_line ORDER BY ts ASC
`

type ListLedgerLinesRow struct {
	Ts        time.Time
	Kind      string
	Provider  string
	Label     string
	Chars     int32
	InTokens  int32
	OutTokens int32
	CostUsd   float64
}

func (q *Queries) ListLedgerLines(ctx context.Context) ([]ListLedgerLinesRow, error) {
	rows, err := q.db.Query(ctx, listLedgerLines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedgerLinesRow{}
	for rows.Next() {
		var i ListLedgerLinesRow
		if err := rows.Scan(
			&i.Ts,
			&i.Kind,
			&i.Provider,
			&i.Label,
			&i.Chars,
			&i.InTokens,
			&i.OutTokens,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistItemIDs = `-- name: ListPlaylistItemIDs :many
SELECT yt_id FROM playlist_item WHERE playlist_id = $1 ORDER BY position
`

func (q *Queries) ListPlaylistItemIDs(ctx context.Context, playlistID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listPlaylistItemIDs, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var yt_id string
		if err := rows.Scan(&yt_id); err != nil {
			return nil, err
		}
		items = append(items, yt_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistItems = `-- name: ListPlaylistItems :many
SELECT ((row_number() OVER (ORDER BY pi.position)) - 1)::int AS position,
       pi.yt_id, t.title, t.channel, t.duration_s::bigint AS duration_s
FROM playlist_item pi
JOIN track t ON t.yt_id = pi.yt_id
WHERE pi.playlist_id = $1
ORDER BY pi.position
`

type ListPlaylistItemsRow struct {
	Position  int32
	YtID      string
	Title     string
	Channel   string
	DurationS int64
}

func (q *Queries) ListPlaylistItems(ctx context.Context, playlistID string) ([]ListPlaylistItemsRow, error) {
	rows, err := q.db.Query(ctx, listPlaylistItems, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaylistItemsRow{}
	for rows.Next() {
		var i ListPlaylistItemsRow
		if err := rows.Scan(
			&i.Position,
			&i.YtID,
			&i.Title,
			&i.Channel,
			&i.DurationS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistRows = `-- name: ListPlaylistRows :many
SELECT p.id::text AS id, p.name, p.created_at, p.updated_at,
       count(pi.yt_id)::int AS track_count,
       COALESCE(sum(t.duration_s), 0)::bigint AS total_duration_s
FROM playlist p
LEFT JOIN playlist_item pi ON pi.playlist_id = p.id
LEFT JOIN track t ON t.yt_id = pi.yt_id
GROUP BY p.id
ORDER BY p.created_at DESC
`

type ListPlaylistRowsRow struct {
	ID             string
	Name           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	TrackCount     int32
	TotalDurationS int64
}

func (q *Queries) ListPlaylistRows(ctx context.Context) ([]ListPlaylistRowsRow, error) {
	rows, err := q.db.Query(ctx, listPlaylistRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlaylistRowsRow{}
	for rows.Next() {
		var i ListPlaylistRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrackCount,
			&i.TotalDurationS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracks = `-- name: ListTracks :many
SELECT yt_id, title, channel, duration_s, artifact_id, input_i, input_tp, input_lra, added_at
FROM track
WHERE ($1 = '' OR title ILIKE '%' || $1 || '%' OR channel ILIKE '%' || $1 || '%')
ORDER BY added_at DESC
LIMIT $2 OFFSET $3
`

type ListTracksParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

func (q *Queries) ListTracks(ctx context.Context, arg ListTracksParams) ([]Track, error) {
	rows, err := q.db.Query(ctx, listTracks, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Track{}
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.YtID,
			&i.Title,
			&i.Channel,
			&i.DurationS,
			&i.ArtifactID,
			&i.InputI,
			&i.InputTp,
			&i.InputLra,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStationRow = `-- name: LockStationRow :one
SELECT COALESCE(active_playlist_id::text, '')::text AS active_playlist_id, on_air, on_air_since
FROM station WHERE id = TRUE FOR UPDATE
`

type LockStationRowRow struct {
	ActivePlaylistID string
	OnAir            bool
	OnAirSince       *time.Time
}

func (q *Queries) LockStationRow(ctx context.Context) (LockStationRowRow, error) {
	row := q.db.QueryRow(ctx, lockStationRow)
	var i LockStationRowRow
	err := row.Scan(&i.ActivePlaylistID, &i.OnAir, &i.OnAirSince)
	return i, err
}

const playlistStats = `-- name: PlaylistStats :one
SELECT count(pi.yt_id)::int AS track_count,
       COALESCE(sum(t.duration_s), 0)::bigint AS total_duration_s
FROM playlist_item pi
JOIN track t ON t.yt_id = pi.yt_id
WHERE pi.playlist_id = $1
`

type PlaylistStatsRow struct {
	TrackCount     int32
	TotalDurationS int64
}

func (q *Queries) PlaylistStats(ctx context.Context, playlistID string) (PlaylistStatsRow, error) {
	row := q.db.QueryRow(ctx, playlistStats, playlistID)
	var i PlaylistStatsRow
	err := row.Scan(&i.TrackCount, &i.TotalDurationS)
	return i, err
}

const renamePlaylist = `-- name: RenamePlaylist :one
UPDATE playlist SET name = $2, updated_at = now() WHERE id = $1
RETURNING id::text AS id, name, created_at, updated_at
`

type RenamePlaylistParams struct {
	ID   string
	Name string
}

type RenamePlaylistRow struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) RenamePlaylist(ctx context.Context, arg RenamePlaylistParams) (RenamePlaylistRow, error) {
	row := q.db.QueryRow(ctx, renamePlaylist, arg.ID, arg.Name)
	var i RenamePlaylistRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setStationActive = `-- name: SetStationActive :exec
UPDATE station SET active_playlist_id = NULLIF($1::text, '')::uuid, updated_at = now() WHERE id = TRUE
`

func (q *Queries) SetStationActive(ctx context.Context, activePlaylistID string) error {
	_, err := q.db.Exec(ctx, setStationActive, activePlaylistID)
	return err
}

const stationGoOffAir = `-- name: StationGoOffAir :one
UPDATE station SET on_air = FALSE, on_air_since = NULL, updated_at = now() WHERE id = TRUE
RETURNING COALESCE(active_playlist_id::text, '')::text AS active_playlist_id, on_air, on_air_since
`

type StationGoOffAirRow struct {
	ActivePlaylistID string
	OnAir            bool
	OnAirSince       *time.Time
}

func (q *Queries) StationGoOffAir(ctx context.Context) (StationGoOffAirRow, error) {
	row := q.db.QueryRow(ctx, stationGoOffAir)
	var i StationGoOffAirRow
	err := row.Scan(&i.ActivePlaylistID, &i.OnAir, &i.OnAirSince)
	return i, err
}

const stationGoOnAir = `-- name: StationGoOnAir :one
UPDATE station SET on_air = TRUE, on_air_since = now(), updated_at = now() WHERE id = TRUE
RETURNING COALESCE(active_playlist_id::text, '')::text AS active_playlist_id, on_air, on_air_since
`

type StationGoOnAirRow struct {
	ActivePlaylistID string
	OnAir            bool
	OnAirSince       *time.Time
}

func (q *Queries) StationGoOnAir(ctx context.Context) (StationGoOnAirRow, error) {
	row := q.db.QueryRow(ctx, stationGoOnAir)
	var i StationGoOnAirRow
	err := row.Scan(&i.ActivePlaylistID, &i.OnAir, &i.OnAirSince)
	return i, err
}

const sumLedgerCost = `-- name: SumLedgerCost :one
SELECT COALESCE(SUM(cost_usd), 0)::double precision AS total FROM ledger_line
`

func (q *Queries) SumLedgerCost(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, sumLedgerCost)
	var total float64
	err := row.Scan(&total)
	return total, err
}
