// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"
)

const insertLedgerLine = `-- name: InsertLedgerLine :exec
INSERT INTO ledger_line (ts, kind, provider, label, chars, in_tokens, out_tokens, cost_usd)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertLedgerLineParams struct {
	Ts        time.Time
	Kind      string
	Provider  string
	Label     string
	Chars     int32
	InTokens  int32
	OutTokens int32
	CostUsd   float64
}

func (q *Queries) InsertLedgerLine(ctx context.Context, arg InsertLedgerLineParams) error {
	_, err := q.db.Exec(ctx, insertLedgerLine,
		arg.Ts,
		arg.Kind,
		arg.Provider,
		arg.Label,
		arg.Chars,
		arg.InTokens,
		arg.OutTokens,
		arg.CostUsd,
	)
	return err
}

const listLedgerLines = `-- name: ListLedgerLines :many
SELECT ts, kind, provider, label, chars, in_tokens, out_tokens, cost_usd
FROM ledger_line ORDER BY ts ASC
`

type ListLedgerLinesRow struct {
	Ts        time.Time
	Kind      string
	Provider  string
	Label     string
	Chars     int32
	InTokens  int32
	OutTokens int32
	CostUsd   float64
}

func (q *Queries) ListLedgerLines(ctx context.Context) ([]ListLedgerLinesRow, error) {
	rows, err := q.db.Query(ctx, listLedgerLines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLedgerLinesRow{}
	for rows.Next() {
		var i ListLedgerLinesRow
		if err := rows.Scan(
			&i.Ts,
			&i.Kind,
			&i.Provider,
			&i.Label,
			&i.Chars,
			&i.InTokens,
			&i.OutTokens,
			&i.CostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumLedgerCost = `-- name: SumLedgerCost :one
SELECT COALESCE(SUM(cost_usd), 0)::double precision AS total FROM ledger_line
`

func (q *Queries) SumLedgerCost(ctx context.Context) (float64, error) {
	row := q.db.QueryRow(ctx, sumLedgerCost)
	var total float64
	err := row.Scan(&total)
	return total, err
}
